/* ============================================================
   data.js — NARIT Dark Sky Thailand  (63 registered sites)
   Source: https://darksky.narit.or.th/darkskyreserve/thailand/
   Coordinates: Official NARIT verified data, April 2026
   Types:   national_park | private | community | suburban
   Regions: North | Northeast | Central | South | West | East
   ============================================================ */

window.DARKSKY_SITES = [

  /* ─── NATIONAL PARKS ──────────────────────────────────── */
  { id:1,  name_en:"Huai Nam Dang National Park",               name_th:"อุทยานแห่งชาติห้วยน้ำดัง",                        province_en:"Chiang Mai",        region:"North",     type:"national_park", lat:19.304379, lng:98.599682, sqm:21.2, bestMonths:[11,12,1,2,3],       facilities:["Camping","High altitude","Ranger station","Sunrise viewpoint"],          url:"https://darksky.narit.or.th/darksky/north/huainamdang-np/" },
  { id:2,  name_en:"Pha Taem National Park",                    name_th:"อุทยานแห่งชาติผาแต้ม",                            province_en:"Ubon Ratchathani",  region:"Northeast", type:"national_park", lat:15.399066, lng:105.507855, sqm:21.3, bestMonths:[11,12,1,2,3,4,5],    facilities:["Rock art","Mekong cliff views","Camping","Rangers"],                      url:"https://darksky.narit.or.th/darksky/northeast/phateam-np/" },
  { id:3,  name_en:"Phu Khiao Wildlife Sanctuary",              name_th:"เขตรักษาพันธุ์สัตว์ป่าภูเขียว",                   province_en:"Chaiyaphum",        region:"Northeast", type:"national_park", lat:16.386748, lng:101.571342, sqm:21.0, bestMonths:[10,11,12,1,2,3],     facilities:["Wildlife sanctuary","Open grassland","Rangers"],                          url:"https://darksky.narit.or.th/darksky/northeast/phukhieo-ws/" },
  { id:4,  name_en:"Pa Hin Ngam National Park",                 name_th:"อุทยานแห่งชาติป่าหินงาม",                         province_en:"Chaiyaphum",        region:"Northeast", type:"national_park", lat:15.631807, lng:101.394653, sqm:null, bestMonths:[10,11,12,1,2,3,4],    facilities:["Unique rock formations","Camping","Wildlife"],                            url:"https://darksky.narit.or.th/darksky/northeast/pahinngam-np/" },
  { id:5,  name_en:"Phu Lan Kha National Park",                 name_th:"อุทยานแห่งชาติภูแลนคา",                           province_en:"Chaiyaphum",        region:"Northeast", type:"national_park", lat:16.000680, lng:101.897263, sqm:21.0, bestMonths:[10,11,12,1,2,3,4],    facilities:["Plateau views","Camping","Forest trails"],                                url:"https://darksky.narit.or.th/darksky/northeast/phulaenkha-np/" },
  { id:6,  name_en:"Mae Wong National Park",                    name_th:"อุทยานแห่งชาติแม่วงก์",                           province_en:"Nakhon Sawan",      region:"Central",   type:"national_park", lat:16.039309, lng:99.233779, sqm:null, bestMonths:[11,12,1,2,3,4,5],    facilities:["Reservoir","Wildlife","Camping","Waterfall"],                             url:"https://darksky.narit.or.th/darksky/center/mae-wong-national-park/" },
  { id:7,  name_en:"Pha Luang Waterfall Forest Park",           name_th:"วนอุทยานน้ำตกผาหลวง",                             province_en:"Ubon Ratchathani",  region:"Northeast", type:"national_park", lat:15.607877, lng:105.379320, sqm:null, bestMonths:[11,12,1,2,3,4,5],    facilities:["Waterfall","Forest trails","Picnic area"],                                url:"https://darksky.narit.or.th/darksky/northeast/namtok-pha-luang-forest-park/" },
  { id:8,  name_en:"Ta Phraya National Park",                   name_th:"อุทยานแห่งชาติตาพระยา",                           province_en:"Sa Kaeo",           region:"East",      type:"national_park", lat:14.141809, lng:102.601695, sqm:null, bestMonths:[11,12,1,2,3,4,5],    facilities:["National park","Camping","Wildlife","Rangers"],                           url:"https://darksky.narit.or.th/darksky/eastern/ta-phraya-national-park/" },
  { id:9,  name_en:"Khao Yai National Park",                    name_th:"อุทยานแห่งชาติเขาใหญ่",                           province_en:"Nakhon Ratchasima", region:"Northeast", type:"national_park", lat:14.222456, lng:101.406249, sqm:20.6, bestMonths:[11,12,1,2,3,4,5],    facilities:["UNESCO Heritage","Lodges","Wildlife tours","Telescopes (events)"],        url:"https://darksky.narit.or.th/darksky/northeast/khao-yai-national-park/" },
  { id:10, name_en:"Si Nan National Park",                      name_th:"อุทยานแห่งชาติศรีน่าน",                           province_en:"Nan",               region:"North",     type:"national_park", lat:18.367883, lng:100.841385, sqm:null, bestMonths:[10,11,12,1,2],       facilities:["Camping","Scenic views","Rangers"],                                       url:"https://darksky.narit.or.th/darksky/north/sri-nan-national-park/" },
  { id:11, name_en:"Tat Ton National Park",                     name_th:"อุทยานแห่งชาติตาดโตน",                            province_en:"Chaiyaphum",        region:"Northeast", type:"national_park", lat:15.981271, lng:102.035836, sqm:null, bestMonths:[10,11,12,1,2,3,4],    facilities:["Waterfall","Camping","Wildlife"],                                         url:"https://darksky.narit.or.th/darksky/northeast/tatton-national-park/" },
  { id:12, name_en:"Sai Thong National Park",                   name_th:"อุทยานแห่งชาติไทรทอง",                            province_en:"Chaiyaphum",        region:"Northeast", type:"national_park", lat:15.875354, lng:101.510076, sqm:null, bestMonths:[10,11,12,1,2,3,4],    facilities:["Camping","Grassland meadow","Scenic plateau"],                            url:"https://darksky.narit.or.th/darksky/northeast/sai-thong-national-park/" },
  { id:13, name_en:"Phu Pha Yon National Park",                 name_th:"อุทยานแห่งชาติภูผายล",                            province_en:"Sakon Nakhon",      region:"Northeast", type:"national_park", lat:16.937915, lng:104.200317, sqm:null, bestMonths:[10,11,12,1,2,3],     facilities:["Camping","Forest trails","Rangers"],                                      url:"https://darksky.narit.or.th/darksky/northeast/phuphayon-national-park/" },
  { id:14, name_en:"Pa Suan Wat Chan — FIO Kalayanaiwattana",   name_th:"ป่าสนวัดจันทร์ อ.อ.ป. กัลยาณิวัฒนา",             province_en:"Chiang Mai",        region:"North",     type:"national_park", lat:19.080946, lng:98.333471, sqm:20.8, bestMonths:[11,12,1,2,3],       facilities:["Camping","Pine forest","Cool climate"],                                   url:"https://darksky.narit.or.th/darksky/north/fio-watchan/" },
  { id:15, name_en:"Phu Wiang National Park",                   name_th:"อุทยานแห่งชาติภูเวียง",                           province_en:"Khon Kaen",         region:"Northeast", type:"national_park", lat:16.698161, lng:102.223786, sqm:null, bestMonths:[11,12,1,2,3,4],      facilities:["Dinosaur fossils","Camping","Scenic ridges"],                             url:"https://darksky.narit.or.th/darksky/northeast/phuwiangnationalpark/" },
  { id:16, name_en:"Namtok Pha Suea — Tham Pla National Park",  name_th:"อุทยานแห่งชาติถ้ำปลา-น้ำตกผาเสื่อ",              province_en:"Mae Hong Son",      region:"North",     type:"national_park", lat:19.498729, lng:97.962609, sqm:null, bestMonths:[11,12,1,2,3],       facilities:["Camping","Fish cave","Waterfall"],                                        url:"https://darksky.narit.or.th/darksky/north/tham-pla-namtok-pha-suea/" },
  { id:17, name_en:"Phu Si Than Wildlife Sanctuary (Tung Non Pa Ko)", name_th:"เขตรักษาพันธุ์สัตว์ป่าภูสีฐาน (ทุ่งโนนป่าก่อ)", province_en:"Mukdahan",    region:"Northeast", type:"national_park", lat:16.600566, lng:104.173522, sqm:21.3, bestMonths:[11,12,1,2,3,4,5],    facilities:["Wildlife sanctuary","Grassland","Ranger station"],                        url:"https://darksky.narit.or.th/darksky/northeast/phu-si-than-wildlife-sanctuary/" },
  { id:18, name_en:"Khao Phra Wihan National Park",             name_th:"อุทยานแห่งชาติเขาพระวิหาร",                       province_en:"Si Sa Ket",         region:"Northeast", type:"national_park", lat:14.417262, lng:104.692751, sqm:null, bestMonths:[11,12,1,2,3,4,5],    facilities:["UNESCO Heritage temple ruins","Cliff views","Camping"],                   url:"https://darksky.narit.or.th/darksky/northeast/khao-phra-wihan-national-park/" },
  { id:19, name_en:"Phu Suan Sai National Park",                name_th:"อุทยานแห่งชาติภูสวนทราย",                         province_en:"Loei",              region:"Northeast", type:"national_park", lat:17.503979, lng:100.940443, sqm:null, bestMonths:[10,11,12,1,2,3],     facilities:["Camping","Waterfall","Scenic plateau"],                                   url:"https://darksky.narit.or.th/darksky/northeast/phu-suan-sai-national-park/" },
  { id:20, name_en:"Phu Hin Rong Kla National Park",            name_th:"อุทยานแห่งชาติภูหินร่องกล้า",                     province_en:"Phitsanulok",       region:"Central",   type:"national_park", lat:17.004005, lng:100.994741, sqm:null, bestMonths:[10,11,12,1,2,3],     facilities:["Historic site","High altitude","Camping","Rangers"],                      url:"https://darksky.narit.or.th/darksky/center/phu-hin-rong-kla/" },
  { id:21, name_en:"Mae Ping National Park",                    name_th:"อุทยานแห่งชาติแม่ปิง",                            province_en:"Lamphun",           region:"North",     type:"national_park", lat:17.596151, lng:98.806208, sqm:null, bestMonths:[11,12,1,2,3],       facilities:["Camping","Rangers","Waterfall trails"],                                   url:"https://darksky.narit.or.th/darksky/north/mae-ping-national-park/" },

  /* ─── COMMUNITY ───────────────────────────────────────── */
  { id:22, name_en:"On Tai Community — San Kamphaeng",          name_th:"บ้านออนใต้ สันกำแพง",                             province_en:"Chiang Mai",        region:"North",     type:"community",     lat:18.716496, lng:99.237136, sqm:null, bestMonths:[11,12,1,2,3],       facilities:["Community events","Guided tours","Local culture"],                        url:"https://darksky.narit.or.th/darksky/north/ontaisan/" },
  { id:23, name_en:"Wat Makut Kiri Wan",                        name_th:"วัดมกุฏคีรีวัน",                                  province_en:"Nakhon Ratchasima", region:"Northeast", type:"community",     lat:14.494666, lng:101.547854, sqm:null, bestMonths:[10,11,12,1,2,3,4,5], facilities:["Temple grounds","Community stargazing","Open field"],                     url:"https://darksky.narit.or.th/darkskyreserve/communities/" },

  /* ─── PRIVATE RESERVES ────────────────────────────────── */
  { id:24, name_en:"The Piano Resort Khao Yai",                 name_th:"โรงแรม เดอะ เปียโน รีสอร์ท เขาใหญ่",             province_en:"Nakhon Ratchasima", region:"Northeast", type:"private",       lat:14.596829, lng:101.372205, sqm:null, bestMonths:[10,11,12,1,2,3,4,5], facilities:["Boutique hotel","Stargazing terrace","Restaurant"],                       url:"https://darksky.narit.or.th/darksky/northeast/thepianoresort/" },
  { id:25, name_en:"Muaklek ATV",                               name_th:"สนามมวกเหล็กเอทีวี",                              province_en:"Saraburi",          region:"Central",   type:"private",       lat:14.744074, lng:101.154255, sqm:null, bestMonths:[10,11,12,1,2,3,4,5], facilities:["ATV field","Open land","Camping"],                                        url:"https://darksky.narit.or.th/darksky/northeast/muaklekatv/" },
  { id:26, name_en:"Alcidini Winery",                           name_th:"ไร่องุ่นไวน์ อัลซิดินี่",                         province_en:"Nakhon Ratchasima", region:"Northeast", type:"private",       lat:14.543758, lng:101.603891, sqm:null, bestMonths:[10,11,12,1,2,3,4],    facilities:["Winery","Vineyard tours","Stargazing"],                                   url:"https://darksky.narit.or.th/darksky/northeast/alcidini-winery/" },
  { id:27, name_en:"Rain Tree Khao Yai Hotel",                  name_th:"โรงแรมเรนทรี เขาใหญ่",                            province_en:"Nakhon Ratchasima", region:"Northeast", type:"private",       lat:14.564878, lng:101.233915, sqm:null, bestMonths:[10,11,12,1,2,3,4,5], facilities:["Hotel","Pool","Stargazing terrace"],                                      url:"https://darksky.narit.or.th/darksky/northeast/raintreekhaoyai/" },
  { id:28, name_en:"Baan Rai Yai Chaplu",                       name_th:"บ้านไร่ยายชะพลู",                                 province_en:"Saraburi",          region:"Central",   type:"private",       lat:14.795408, lng:101.258249, sqm:null, bestMonths:[10,11,12,1,2,3,4],    facilities:["Farm","Homestay","Open field"],                                           url:"https://darksky.narit.or.th/darksky/northeast/chaplu/" },
  { id:29, name_en:"GranMonte Vineyard and Winery",             name_th:"ไร่องุ่นไวน์กราน-มอนเต้",                         province_en:"Nakhon Ratchasima", region:"Northeast", type:"private",       lat:14.568519, lng:101.278763, sqm:null, bestMonths:[10,11,12,1,2,3,4],    facilities:["Winery","Stargazing events","Restaurant","Accommodation"],                url:"https://darksky.narit.or.th/darksky/northeast/granmonte/" },
  { id:30, name_en:"Mela Garden Retreat Cottage",               name_th:"มีลา การ์เดน รีทรีท คอทเทจ",                     province_en:"Saraburi",          region:"Central",   type:"private",       lat:14.874424, lng:101.333361, sqm:null, bestMonths:[10,11,12,1,2,3,4],    facilities:["Garden cottage","Stargazing","Peaceful retreat"],                         url:"https://darksky.narit.or.th/darksky/center/mela-garden-retreat-cottage/" },
  { id:31, name_en:"Khirimala Eco Camp",                        name_th:"คีรีมาลา อีโค่ แคมป์",                            province_en:"Ratchaburi",        region:"West",      type:"private",       lat:13.590929, lng:99.234891, sqm:null, bestMonths:[11,12,1,2,3,4],      facilities:["Eco camp","Stargazing events","Open field"],                              url:"https://darksky.narit.or.th/darksky/western/khirimala/" },
  { id:32, name_en:"Villa De View — Chiang Dao",                name_th:"วิลลา เดอ วิว บูทีค รีสอร์ท เชียงดาว",           province_en:"Chiang Mai",        region:"North",     type:"private",       lat:19.405927, lng:98.925450, sqm:null, bestMonths:[11,12,1,2,3],       facilities:["Boutique resort","Mountain views","Guided stargazing"],                   url:"https://darksky.narit.or.th/darksky/north/villa-de-view-chiang-dao/" },
  { id:33, name_en:"Unfah Ing Dao Camping",                     name_th:"อุ่นฟ้าอิงดาวแคมป์ปิ้ง",                         province_en:"Nakhon Ratchasima", region:"Northeast", type:"private",       lat:14.395872, lng:101.878554, sqm:null, bestMonths:[10,11,12,1,2,3,4],    facilities:["Camping","Open field","Stargazing events"],                               url:"https://darksky.narit.or.th/darksky/northeast/unfar-camping/" },
  { id:34, name_en:"Rai Khao Noi Suwana Observatory",           name_th:"ไร่เขาน้อยสุวณา",                                 province_en:"Nakhon Ratchasima", region:"Northeast", type:"private",       lat:14.571880, lng:101.438540, sqm:null, bestMonths:[10,11,12,1,2,3,4],    facilities:["Farm","Observatory","Nature learning centre"],                            url:"https://darksky.narit.or.th/darksky/northeast/observatory-for-stargazing-and-nature-learning-cener/" },
  { id:35, name_en:"Golden Cliff Beach Resort — Koh Kood",      name_th:"โกลเด้น คลิฟ บีช รีสอร์ท",                       province_en:"Trat",              region:"East",      type:"private",       lat:12.005668, lng:102.767580, sqm:null, bestMonths:[11,12,1,2,3,4],      facilities:["Beach resort","Cliff views","Sea horizon","Stargazing"],                  url:"https://darksky.narit.or.th/darksky/eastern/golden-cliff-beach-resort/" },
  { id:36, name_en:"Soneva Kiri Private Reserve — Koh Kood",    name_th:"โรงแรมโซเนวา คีรี",                               province_en:"Trat",              region:"East",      type:"private",       lat:11.699409, lng:102.532927, sqm:null, bestMonths:[11,12,1,2,3,4],      facilities:["Luxury resort","Private island","Telescope","Butler service"],            url:"https://darksky.narit.or.th/darksky/eastern/soneva-kiri-koh-kood/" },
  { id:37, name_en:"Homelomjoy — Chiang Rai",                   name_th:"ฮ่อมลมจอย",                                       province_en:"Chiang Rai",        region:"North",     type:"private",       lat:19.706335, lng:99.760972, sqm:null, bestMonths:[11,12,1,2],          facilities:["Accommodation","Guided tours","Mountain views"],                          url:"https://darksky.narit.or.th/darksky/north/homelomjoy/" },
  { id:38, name_en:"Suan Pailin Astro Park",                    name_th:"สวนไพลินชมดารา",                                  province_en:"Nakhon Ratchasima", region:"Northeast", type:"private",       lat:14.698380, lng:101.455145, sqm:19.0, bestMonths:[10,11,12,1,2,3,4,5], facilities:['14" & 16" telescopes','4 imaging domes','Camping 15 units','Expert guides'], phone:"085-492-5557", url:"https://darksky.narit.or.th/darksky/northeast/pailinastropark/" },
  { id:39, name_en:"Phrao Camping Village",                     name_th:"พร้าวแคมป์ปิ้ง วิลเลจ",                           province_en:"Chiang Mai",        region:"North",     type:"private",       lat:19.366199, lng:99.167731, sqm:null, bestMonths:[11,12,1,2,3],       facilities:["Glamping","Camping","Mountain views"],                                    url:"https://darksky.narit.or.th/darksky/north/phraocampingvillage/" },
  { id:40, name_en:"Eco Garden Camp — Nakhon Sawan",            name_th:"ภาวนานิเวศน์ แคมป์",                              province_en:"Nakhon Sawan",      region:"Central",   type:"private",       lat:15.655845, lng:99.793543, sqm:null, bestMonths:[11,12,1,2,3,4],      facilities:["Eco camp","Open field","Mindfulness retreat"],                            url:"https://darksky.narit.or.th/darksky/center/ecogardencamp/" },
  { id:41, name_en:"Borsaen Villa — Krabi",                     name_th:"บ่อแสนวิลล่า",                                    province_en:"Krabi",             region:"South",     type:"private",       lat:8.466884,  lng:98.591067, sqm:null, bestMonths:[11,12,1,2,3,4],      facilities:["Villa","Sea views","Dark sky terrace"],                                   url:"https://darksky.narit.or.th/darksky/south/borsaen-villa/" },
  { id:42, name_en:"Ao Tho Li Viewpoint",                       name_th:"จุดชมวิว อ่าวโต๊ะหลี",                            province_en:"Phang Nga",         region:"South",     type:"private",       lat:8.226500,  lng:98.445490, sqm:null, bestMonths:[11,12,1,2,3,4],      facilities:["Viewpoint","Bay panorama","Astrophotography spot"],                       url:"https://darksky.narit.or.th/darksky/south/toh-li-view-point/" },
  { id:43, name_en:"AThi Garden Camping — Phang Nga",           name_th:"อธิการ์เด้นแคมป์ปิ้ง",                            province_en:"Phang Nga",         region:"South",     type:"private",       lat:8.573015,  lng:98.368020, sqm:null, bestMonths:[11,12,1,2,3,4],      facilities:["Camping","Dark sky garden","Beach access"],                               url:"https://darksky.narit.or.th/darksky/south/athigardencamping/" },
  { id:44, name_en:"Cha Ger Por — Chiang Dao",                  name_th:"ฉ่าเก่อปอ",                                       province_en:"Chiang Mai",        region:"North",     type:"private",       lat:19.363417, lng:98.930060, sqm:null, bestMonths:[11,12,1,2,3],       facilities:["Camping","Stargazing events","Open field"],                               url:"https://darksky.narit.or.th/darksky/north/chagerporchiangdao/" },
  { id:45, name_en:"Phukumhom Resort — Khao Yai",               name_th:"ภูคำหอม รีสอร์ท",                                 province_en:"Nakhon Ratchasima", region:"Northeast", type:"private",       lat:14.537719, lng:101.602200, sqm:null, bestMonths:[10,11,12,1,2,3,4],    facilities:["Resort","Telescopes","Food service","Guided sessions"],                   url:"https://darksky.narit.or.th/darksky/northeast/phukumhomkhaoyaiwangkata/" },
  { id:46, name_en:"Baan Rai Nai Kaew — Khon Kaen",             name_th:"บ้านไร่นายเขียว",                                 province_en:"Khon Kaen",         region:"Northeast", type:"private",       lat:16.640856, lng:102.294722, sqm:null, bestMonths:[10,11,12,1,2,3,4,5], facilities:["Farm stay","Open sky","Food"],                                            url:"https://darksky.narit.or.th/darksky/northeast/baan-rai-nai-kaew/" },
  { id:47, name_en:"Daraga — Chiang Dao",                       name_th:"ดารกะ เชียงดาว",                                  province_en:"Chiang Mai",        region:"North",     type:"private",       lat:19.337200, lng:98.985573, sqm:null, bestMonths:[11,12,1,2,3],       facilities:["Resort","Telescope","Astrophotography sessions"],                         url:"https://darksky.narit.or.th/darksky/north/daraga-chiang-dao/" },
  { id:48, name_en:"Wanathara Resort — Phitsanulok",            name_th:"วนธารา รีสอร์ท",                                  province_en:"Phitsanulok",       region:"Central",   type:"private",       lat:16.876862, lng:100.639691, sqm:null, bestMonths:[10,11,12,1,2,3,4],    facilities:["Forest resort","Astrophotography events","Restaurant"],                   url:"https://darksky.narit.or.th/darksky/center/wanathara/" },
  { id:49, name_en:"Mae Lamao Forest Park — FIO Tak",           name_th:"สวนป่าแม่ละเมา องค์การอุตสาหกรรมป่าไม้",          province_en:"Tak",               region:"West",      type:"private",       lat:16.764239, lng:98.749803, sqm:null, bestMonths:[11,12,1,2,3,4],      facilities:["Forest park","Camping","Mountain views"],                                 url:"https://darksky.narit.or.th/darksky/western/mae-lamao/" },
  { id:50, name_en:"Dara Cuisine — Phuket",                     name_th:"ดาราควิซีน",                                      province_en:"Phuket",            region:"South",     type:"private",       lat:8.043427,  lng:98.298929, sqm:null, bestMonths:[11,12,1,2,3,4],      facilities:["Restaurant","Rooftop stargazing","Telescope"],                            url:"https://darksky.narit.or.th/darksky/south/dara-cuisine/" },
  { id:51, name_en:"Phu Prom Dao Farmstay",                     name_th:"ภูพร้อมดาว ฟาร์มสเตย์",                           province_en:"Chaiyaphum",        region:"Northeast", type:"private",       lat:15.616087, lng:101.401376, sqm:null, bestMonths:[10,11,12,1,2,3,4,5], facilities:["Farmstay","Open field","Telescope","Food service"],                       url:"https://darksky.narit.or.th/darksky/northeast/phu-prom-dao-farmstay/" },
  { id:52, name_en:"Fountain Tree Resort",                      name_th:"ฟาวน์เท่นทรี รีสอร์ท",                            province_en:"Nakhon Ratchasima", region:"Northeast", type:"private",       lat:14.658743, lng:101.454962, sqm:null, bestMonths:[10,11,12,1,2,3,4],    facilities:["Resort","Pool","Stargazing events","Restaurant"],                         url:"https://darksky.narit.or.th/darksky/northeast/fountaintree-resort/" },
  { id:53, name_en:"Doi Tung Royal Villa — Mae Fah Luang",      name_th:"สวนแม่ฟ้าหลวง",                                   province_en:"Chiang Rai",        region:"North",     type:"private",       lat:20.288743, lng:99.809945, sqm:null, bestMonths:[11,12,1,2],          facilities:["Gardens","Guided events","Visitor centre"],                               url:"https://darksky.narit.or.th/darksky/north/mae-fah-luang-foundation-under-royal-patronage/" },

  /* ─── SUBURBAN / OBSERVATORY ──────────────────────────── */
  { id:54, name_en:"Princess Sirindhorn AstroPark",             name_th:"อุทยานดาราศาสตร์สิรินธร",                         province_en:"Chiang Mai",        region:"North",     type:"suburban",      lat:18.853570, lng:98.958558, sqm:19.5, bestMonths:[10,11,12,1,2,3,4],    facilities:["Telescopes","Planetarium","Education centre","Events","Parking"],         url:"https://darksky.narit.or.th/darksky/north/astropark/" },
  { id:55, name_en:"Regional Observatory — Nakhon Ratchasima", name_th:"หอดูดาวเฉลิมพระเกียรติฯ นครราชสีมา",             province_en:"Nakhon Ratchasima", region:"Northeast", type:"suburban",      lat:14.874242, lng:102.028657, sqm:18.5, bestMonths:[10,11,12,1,2,3,4,5,6], facilities:["NARIT observatory","Public events","Education"],                          url:"https://darksky.narit.or.th/darksky/northeast/nma/" },
  { id:56, name_en:"Regional Observatory — Chachoengsao",      name_th:"หอดูดาวเฉลิมพระเกียรติฯ ฉะเชิงเทรา",             province_en:"Chachoengsao",      region:"Central",   type:"suburban",      lat:13.593784, lng:101.256946, sqm:18.5, bestMonths:[10,11,12,1,2,3,4,5,6], facilities:["NARIT observatory","Public events","Education"],                          url:"https://darksky.narit.or.th/darksky/center/cco/" },
  { id:57, name_en:"Songkhla Regional Observatory",            name_th:"หอดูดาวเฉลิมพระเกียรติฯ สงขลา",                  province_en:"Songkhla",          region:"South",     type:"suburban",      lat:7.158289,  lng:100.611783, sqm:18.5, bestMonths:[10,11,12,1,2,3,4,5,6], facilities:["NARIT observatory","Education","Public events"],                          url:"https://darksky.narit.or.th/darksky/south/ska/" },
  { id:58, name_en:"Regional Observatory — Khon Kaen",         name_th:"หอดูดาวเฉลิมพระเกียรติฯ ขอนแก่น",               province_en:"Khon Kaen",         region:"Northeast", type:"suburban",      lat:16.761654, lng:102.632078, sqm:18.5, bestMonths:[10,11,12,1,2,3,4,5,6], facilities:["NARIT observatory","Public events","Education"],                          url:"https://darksky.narit.or.th/darksky/northeast/kkn/" },
  { id:59, name_en:"Khon Kaen Zoo",                            name_th:"สวนสัตว์ขอนแก่น",                                  province_en:"Khon Kaen",         region:"Northeast", type:"suburban",      lat:16.845310, lng:102.897231, sqm:null, bestMonths:[10,11,12,1,2,3,4,5], facilities:["Zoo","Night events","Parking"],                                           url:"https://darksky.narit.or.th/darksky/northeast/khonkaen-zoo/" },
  { id:60, name_en:"Summit Green Valley Chiang Mai Country Club", name_th:"ซัมมิท กรีน วัลเล่ย์ เชียงใหม่ คันทรี คลับ", province_en:"Chiang Mai",        region:"North",     type:"suburban",      lat:18.907885, lng:98.958837, sqm:null, bestMonths:[11,12,1,2,3],       facilities:["Country club","Events","Parking"],                                        url:"https://darksky.narit.or.th/darksky/north/summit-green-valley-chiang-mai/" },
  { id:61, name_en:"Khao Kheow Open Zoo",                      name_th:"สวนสัตว์เปิดเขาเขียว",                              province_en:"Chon Buri",         region:"East",      type:"suburban",      lat:13.215629, lng:101.053936, sqm:null, bestMonths:[10,11,12,1,2,3,4,5], facilities:["Open zoo","Night events","Education"],                                    url:"https://darksky.narit.or.th/darksky/eastern/khao-kheow-open-zoo/" },
  { id:62, name_en:"Elephant Kingdom Surin",                   name_th:"คชอาณาจักรสุรินทร์",                               province_en:"Surin",             region:"Northeast", type:"suburban",      lat:15.252977, lng:103.491779, sqm:null, bestMonths:[10,11,12,1,2,3,4,5], facilities:["Elephant sanctuary","Events","Cultural activities"],                      url:"https://darksky.narit.or.th/darksky/northeast/elephant-kingdom/" },
  { id:63, name_en:"Walai Rukhavej Botanical Garden — MSU",    name_th:"สวนวลัยรุกขเวช มหาวิทยาลัยมหาสารคาม",             province_en:"Maha Sarakham",     region:"Northeast", type:"suburban",      lat:16.235307, lng:103.334511, sqm:null, bestMonths:[10,11,12,1,2,3,4,5,6], facilities:["Observatory","Education programs","Free parking"],                        url:"https://darksky.narit.or.th/darksky/northeast/walairukhavej/" },

];

/* ── Lookup tables ─────────────────────────────────────── */
window.MONTHS = ['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
window.DAYS   = ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'];

window.TYPE_LABELS = {
  national_park: '🌿 National Park',
  private:       '🔭 Private / Resort',
  community:     '🏘 Community',
  suburban:      '🏙 Observatory / Suburban',
};

window.BORTLE_DESC = [
  '',
  'Zodiacal Light & IFN visible',
  'Zodiacal Light clearly visible',
  'Milky Way structure clearly visible',
  'Milky Way easily seen',
  'Milky Way still visible',
  'Milky Way difficult to see',
  'Milky Way very faint',
  'City horizon glow',
  'Full sky dome visible',
];
